### ISSUE TITLE
Credit and Licensing

### ISSUE THREAD

**Issue by isabelroses** [rose-pine/userstyles#17]
The userstyles that are adapted from [catppuccin/userstyles](https://github.com/catppuccin/userstyles) should be credited to the org and not the the original creator of the given userstyle.

Thanks for your time.

**Comment by trinkey** [comment]
they're ignoring you

**Comment by mvllow** [comment]
@adriankarlen are you up to make this change? If not I can change the attributions in the near future.

Thanks for bringing this to our attention. Making my way through a backlog of issues after being away for personal reasons.

**Comment by uncenter** [comment]
Hi there! Thank you for adding attribution to Catppuccin in the READMEs! I was taking a look at what y'all've got going on here and I'm noticing a few userstyles are extremely similar to our existing userstyles, beyond inspiration. Could you add a proper `LICENSE`/`LICENSE.txt` file, at least for the userstyles copied from https://github.com/catppuccin/userstyles?

One other thing - this might be a long stretch but I think it would be easier for y'all to fork our userstyles repository and setup a custom syncing and migration CI? I'm thinking a workflow where the newest userstyles and changes are pulled from our repository regex to replace the color names, palette, and metadata is applied... our userstyles are incredibly consistent in terms of metadata and palette (thanks to our linter!) so you shouldn't have any weird edge cases with a migration script like I've mentioned.
