### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by uncenter** [rose-pine/userstyles#25]
Hi! Left a comment on #17 regarding some issues with attribution and licesning a week ago (https://github.com/rose-pine/userstyles/issues/17#issuecomment-2201208412) with no response. Bumping this as a new issue for visibility. Comment from earlier is pasted below for clarity:

> Hi there! Thank you for adding attribution to Catppuccin in the READMEs! I was taking a look at what y'all've got going on here and I'm noticing a few userstyles are extremely similar to our existing userstyles, beyond inspiration. Could you add a proper `LICENSE`/`LICENSE.txt` file, at least for the userstyles copied from https://github.com/catppuccin/userstyles? You should also probably have a root level Rose Pine license in the repository, like https://github.com/rose-pine/rose-pine-theme/blob/main/license.

**Comment by adriankarlen** [comment]
Hi, am I understanding it correctly that the issue is that the repo currently does not have license when the ported styles do?

I am not part of the org but I assume the same license used on the theme should be applied, which is the same as the themes ported so I assume we could simply add it.

**Comment by uncenter** [comment]
That but also the styles that are copied from catppuccin/userstyles should have better attribution in the form of a separate `LICENSE` file for Catppuccin in the appropriate directories.

**Comment by mvllow** [comment]
Thanks for bringing this to our attention. I added a license to the main repo as well as each specific userstyle. I simply looked at the readme attribution and if Catppuccin Org was mentioned I prepended the license with the original license.
